### ISSUE TITLE
Misleading config option

### ISSUE THREAD

**Issue by VaguelyOnline** [kurbanatabinen/pulsegpt#1]
The comment against the cache time value here:

https://github.com/kurbanatabinen/pulsegpt/blob/main/config/pulsegpt.php

...Is that it is in milliseconds. However, the docs state the cache time is in seconds, as per: https://laravel.com/docs/10.x/cache#retrieve-store.

**Comment by kurbanatabinen** [comment]
Thanks, fixed 8 months after :)
